/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action.dean;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.li.service.inters.SubjectServiceInter;
import com.li.struts.form.dean.NotAccessQuestionForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-28-2014
 * 
 * XDoclet definition:
 * @struts.action
 */
public class NotAccessQuestionAction extends Action {
	@Resource
	private SubjectServiceInter subjectServiceInter;
	public void setSubjectServiceInter(SubjectServiceInter subjectServiceInter) {
		this.subjectServiceInter = subjectServiceInter;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		NotAccessQuestionForm notAccessQuestionForm = (NotAccessQuestionForm)form;
		String subjectId_str = notAccessQuestionForm.getSubjectId();
		String subjectSuggest = notAccessQuestionForm.getSubjectInfo();
		int subjectId = Integer.parseInt(subjectId_str);
		
		subjectServiceInter.notAccessSubject(subjectId, subjectSuggest);
		
		ActionForward actionForward = new ActionForward();
		actionForward.setPath("/deanUrl.do?flag=deanCheckQuestion");
		
		return actionForward;
	}
}