/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.form.dean;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-28-2014
 * 
 * XDoclet definition:
 * @struts.form name="confirmSubjectForm"
 */
public class ConfirmSubjectForm extends ActionForm {
	private String volunteerTurn;
	public String getVolunteerTurn() {
		return volunteerTurn;
	}
	public void setVolunteerTurn(String volunteerTurn) {
		this.volunteerTurn = volunteerTurn;
	}

}