/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.form.dean;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-05-2014
 * 
 * XDoclet definition:
 * @struts.form name="notAccessQuestionForm"
 */
public class NotAccessQuestionForm extends ActionForm {
	private String subjectId;
	private String subjectInfo;
	public String getSubjectId() {
		return subjectId;
	}
	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}
	public String getSubjectInfo() {
		return subjectInfo;
	}
	public void setSubjectInfo(String subjectInfo) {
		this.subjectInfo = subjectInfo;
	}
}