/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action.teacher;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.envers.reader.FirstLevelCache;

import com.li.domain.Teacher;
import com.li.service.inters.CommentServiceInter;
import com.li.struts.form.teacher.InputFirstAssessForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-09-2014
 * 
 * XDoclet definition:
 * @struts.action
 */
public class InputFirstAssessAction extends Action {
	@Resource
	private CommentServiceInter commentServiceInter;
	public void setCommentServiceInter(CommentServiceInter commentServiceInter) {
		this.commentServiceInter = commentServiceInter;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		InputFirstAssessForm inputFirstAssessForm = (InputFirstAssessForm)form;
		
		String studentId = inputFirstAssessForm.getStudentId();
		String studentScore = inputFirstAssessForm.getStudentScore();
		String studentComment = inputFirstAssessForm.getStudentComment();
		
		Teacher teacher = (Teacher) request.getSession().getAttribute("teacher");
		
		commentServiceInter.inputFirst(studentId, studentScore, studentComment, teacher.getId());
		
		
		return mapping.findForward("teacherMain");
	}
}