/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action.teacher;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.li.domain.Teacher;
import com.li.service.inters.TeacherServiceInter;
import com.li.struts.form.teacher.TeacherChangePwdForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-02-2014
 * 
 * XDoclet definition:
 * @struts.action
 */
public class TeacherChangePwdAction extends Action {
	@Resource
	private TeacherServiceInter teacherServiceInter;
	public void setTeacherServiceInter(TeacherServiceInter teacherServiceInter) {
		this.teacherServiceInter = teacherServiceInter;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		TeacherChangePwdForm teacherChangePwdForm = (TeacherChangePwdForm)form;
		
		String oldPwd = teacherChangePwdForm.getOldPwd();
		String newPwd = teacherChangePwdForm.getNewPwd();
		
		Teacher teacher = (Teacher) request.getSession().getAttribute("teacher");
		boolean success = teacherServiceInter.changePwd(teacher, oldPwd, newPwd);
		
		if(success){
			return mapping.findForward("teacherOk");
		}
		else{
			return mapping.findForward("teacherError");
		}
		
	}
}