/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action.teacher;

import java.util.Calendar;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.li.domain.Major;
import com.li.domain.Subject;
import com.li.domain.SubjectType;
import com.li.domain.Teacher;
import com.li.service.imp.SubjectTypeService;
import com.li.service.inters.MajorServiceInter;
import com.li.service.inters.SubjectServiceInter;
import com.li.service.inters.SubjectTypeServiceInter;
import com.li.struts.form.teacher.UploadQuestionForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-19-2014
 * 
 * XDoclet definition:
 * @struts.action path="/uploadQuestion" name="uploadQuestionForm" scope="request"
 */
public class UploadQuestionAction extends Action {
	@Resource
	private MajorServiceInter majorServiceInter;
	@Resource
	private SubjectTypeServiceInter subjectTypeServiceInter;
	@Resource
	private SubjectServiceInter subjectServiceInter;
	public void setMajorServiceInter(MajorServiceInter majorServiceInter) {
		this.majorServiceInter = majorServiceInter;
	}
	public void setSubjectTypeServiceInter(
			SubjectTypeServiceInter subjectTypeServiceInter) {
		this.subjectTypeServiceInter = subjectTypeServiceInter;
	}
	public void setSubjectServiceInter(SubjectServiceInter subjectServiceInter) {
		this.subjectServiceInter = subjectServiceInter;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UploadQuestionForm uploadQuestionForm = (UploadQuestionForm) form;// TODO Auto-generated method stub
		
		int questionType = Integer.parseInt(uploadQuestionForm.getQuestionType());
		SubjectType subjectType = (SubjectType) subjectTypeServiceInter.findById(SubjectType.class, questionType);
		
		String questionName = uploadQuestionForm.getQuestionName();
		
		int questionMajor = Integer.parseInt(uploadQuestionForm.getQuestionMajor());
		Major major = (Major) majorServiceInter.findById(Major.class, questionMajor);
		
		String questionInfo = uploadQuestionForm.getQuestionInfo();
		
		Calendar calendar = Calendar.getInstance();
		int grade = calendar.get(Calendar.YEAR);
		
		Teacher teacher = (Teacher)request.getSession().getAttribute("teacher");
		
//		Subject subject = new Subject(teacher, major, subjectType, questionName, grade + "", questionInfo, 0);
		Subject subject = new Subject(teacher, major, subjectType, questionName, grade + "", questionInfo);
		subject.setSubjectYes(0);
		subjectServiceInter.add(subject);
		
		return mapping.findForward("teacherOk");
	}
}