/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.li.domain.Dept;
import com.li.domain.Major;
import com.li.domain.Notice;
import com.li.domain.SystemStatus;
import com.li.service.inters.DeptServiceInter;
import com.li.service.inters.MajorServiceInter;
import com.li.service.inters.NoticeServiceInter;
import com.li.service.inters.SystemStatusServiceInter;
import com.li.util.Constants;

/** 
 * MyEclipse Struts
 * Creation date: 05-26-2014
 * s
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class AdminUrlAction extends DispatchAction {
	@Resource
	private DeptServiceInter deptServiceInter;
	@Resource
	private MajorServiceInter majorServiceInter;
	@Resource
	private SystemStatusServiceInter systemStatusServiceInter;
	@Resource
	private NoticeServiceInter noticeServiceInter;
	public void setDeptServiceInter(DeptServiceInter deptServiceInter) {
		this.deptServiceInter = deptServiceInter;
	}
	public void setNoticeServiceInter(NoticeServiceInter noticeServiceInter) {
		this.noticeServiceInter = noticeServiceInter;
	}
	public void setMajorServiceInter(MajorServiceInter majorServiceInter) {
		this.majorServiceInter = majorServiceInter;
	}
	public void setSystemStatusServiceInter(
			SystemStatusServiceInter systemStatusServiceInter) {
		this.systemStatusServiceInter = systemStatusServiceInter;
	}
	public ActionForward adminBulkChanges(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("adminBulkChanges");
	}
	public ActionForward adminMain(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<Notice> notices = noticeServiceInter.loadNoticesByGrade(Constants.Notice_Constants.NOTICE_GRADE_TEACHER);
		request.setAttribute("notices", notices);
		
		return mapping.findForward("adminMain");
	}
	public ActionForward adminOk(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("adminOk");
	}
	public ActionForward adminQueryStudent(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<Major> majors = majorServiceInter.loadMajors();
		
		request.getSession().setAttribute("majors", majors);
		
		return mapping.findForward("adminQueryStudent");
	}
	public ActionForward adminQueryTeacher(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		
		return mapping.findForward("adminQueryTeacher");
	}
	public ActionForward adminResetPwd(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("adminResetPwd");
	}
	public ActionForward adminStatistics(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("adminStatistics");
	}
	public ActionForward adminUploadClazz(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("adminUploadClazz");
	}
	public ActionForward adminUploadDept(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("adminUploadDept");
	}
	public ActionForward adminUploadMajor(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("adminUploadMajor");
	}
	public ActionForward adminUploadStudent(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("adminUploadStudent");
	}
	public ActionForward adminUploadTeacher(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("adminUploadTeacher");
	}
	public ActionForward adminError(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("adminError");
	}
	public ActionForward adminChangeStatus(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		SystemStatus systemStatus = null;
		
		systemStatus = systemStatusServiceInter.loadSystemStatusById(1);
		request.getSession().setAttribute("status1", systemStatus.getSystemStatus());
		
		systemStatus = systemStatusServiceInter.loadSystemStatusById(2);
		request.getSession().setAttribute("status2", systemStatus.getSystemStatus());
		
		systemStatus = systemStatusServiceInter.loadSystemStatusById(3);
		request.getSession().setAttribute("status3", systemStatus.getSystemStatus());
		
		systemStatus = systemStatusServiceInter.loadSystemStatusById(4);
		request.getSession().setAttribute("status4", systemStatus.getSystemStatus());
		
		return mapping.findForward("adminChangeStatus");
	}
	public ActionForward adminCalendar(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("adminCalendar");
	}
	public ActionForward adminLogout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("login");
	}
}