/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.li.domain.Major;
import com.li.domain.Notice;
import com.li.domain.Subject;
import com.li.domain.SubjectType;
import com.li.domain.SystemStatus;
import com.li.domain.Teacher;
import com.li.domain.TeacherGroup;
import com.li.service.inters.NoticeServiceInter;
import com.li.service.inters.SubjectServiceInter;
import com.li.service.inters.SystemStatusServiceInter;
import com.li.service.inters.TeacherGroupServiceInter;
import com.li.util.Constants;
import com.li.web.domain.TeacherGroupWeb;

/** 
 * MyEclipse Struts
 * Creation date: 05-26-2014
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class DeanUrlAction extends DispatchAction {
	@Resource
	private SubjectServiceInter subjectServiceInter;
	@Resource
	private SystemStatusServiceInter systemStatusServiceInter;
	@Resource
	private NoticeServiceInter noticeServiceInter;
	@Resource
	private TeacherGroupServiceInter teacherGroupServiceInter;
	public void setTeacherGroupServiceInter(
			TeacherGroupServiceInter teacherGroupServiceInter) {
		this.teacherGroupServiceInter = teacherGroupServiceInter;
	}
	public void setSubjectServiceInter(SubjectServiceInter subjectServiceInter) {
		this.subjectServiceInter = subjectServiceInter;
	}
	public void setNoticeServiceInter(NoticeServiceInter noticeServiceInter) {
		this.noticeServiceInter = noticeServiceInter;
	}
	public void setSystemStatusServiceInter(
			SystemStatusServiceInter systemStatusServiceInter) {
		this.systemStatusServiceInter = systemStatusServiceInter;
	}
	public ActionForward deanAssessGroup(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<TeacherGroupWeb> teacherGroupsWeb = new ArrayList<TeacherGroupWeb>();
		
		int lastTeacherGroupId = teacherGroupServiceInter.getLastTeacherGroupId();
		System.out.println("DeanUrlAction::deanAssessGroup::lastTeacherGroupId=" + lastTeacherGroupId);
		
		for(int i = 1;i <= lastTeacherGroupId;i++){
			List<TeacherGroup> teacherGroups = teacherGroupServiceInter.loadTeacherGroupsById(i);
			
			System.out.println("DeanUrlAction::deanAssessGroup::teacherGroups.size=" + teacherGroups.size());
			TeacherGroupWeb teacherGroupWeb = new TeacherGroupWeb();
			teacherGroupWeb.setTeacherGroups(teacherGroups);
			teacherGroupsWeb.add(teacherGroupWeb);
		}
		
		request.getSession().setAttribute("teacherGroupsWeb", teacherGroupsWeb);
		System.out.println("DeanUrlAction::deanAssessGroup::teacherGroupsWeb.size=" + teacherGroupsWeb.size());
		
		return mapping.findForward("deanAssessGroup");
	}
	
	public ActionForward deanCheckQuestion(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		Teacher teacher = (Teacher) request.getSession().getAttribute("teacher");
		List<Subject> subjects = subjectServiceInter.loadSubjectsNotYesByMajor(teacher.getId());
		
		request.getSession().setAttribute("subjects", subjects);
		
		return mapping.findForward("deanCheckQuestion");
	}
	public ActionForward deanConfirmVolunteer(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("deanConfirmVolunteer");
	}
	public ActionForward deanMain(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<Notice> notices = noticeServiceInter.loadNoticesByGrade(Constants.Notice_Constants.NOTICE_GRADE_TEACHER);
		request.setAttribute("notices", notices);
		
		return mapping.findForward("deanMain");
	}
	public ActionForward deanOk(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("deanOk");
	}
	public ActionForward deanReplyGroup(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("deanReplyGroup");
	}
	public ActionForward deanError(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("deanError");
	}
	public ActionForward deanConfirmVolunteerThree(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("deanConfirmVolunteerThree");
	}
	public ActionForward deanCalendar(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("deanCalendar");
	}
	public ActionForward deanLogout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("login");
	}
}