/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.li.domain.Student;
import com.li.domain.Teacher;
import com.li.service.inters.StudentServiceInter;
import com.li.service.inters.TeacherServiceInter;
import com.li.struts.form.LoginForm;
import com.li.util.Constants;

/** 
 * MyEclipse Struts
 * Creation date: 05-19-2014
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" scope="request"
 */
public class LoginAction extends Action {
	@Resource
	private StudentServiceInter studentServiceInter;
	@Resource
	private TeacherServiceInter teacherServiceInter;
	public void setStudentServiceInter(StudentServiceInter studentServiceInter) {
		this.studentServiceInter = studentServiceInter;
	}
	public void setTeacherServiceInter(TeacherServiceInter teacherServiceInter) {
		this.teacherServiceInter = teacherServiceInter;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		String username = loginForm.getUsername();
		String password = loginForm.getPassword();
		
		if (username.length() == 8) {// 学生
			Student student = studentServiceInter.login(username, password);
			if (student != null) {
				request.getSession().setAttribute("student", student);
				ActionForward actionForward = new ActionForward();
				actionForward.setPath("/studentUrl.do?flag=studentMain");
				return actionForward;
			} else {
				return mapping.findForward("login");
			}
		} else {// 老师
			if (username.equals("admin") && password.equals("admin")) {
				ActionForward actionForward = new ActionForward();
				actionForward.setPath("/adminUrl.do?flag=adminMain");
				return actionForward;
			} else {
				Teacher teacher = teacherServiceInter.login(username, password);
				if (teacher != null) {
					int teacherGrade = teacher.getTeacherGrade();
					
					request.getSession().setAttribute("teacher", teacher);
					if (teacherGrade == Constants.Teacher_Constants.TEACHER) {
						ActionForward actionForward = new ActionForward();
						actionForward.setPath("/teacherUrl.do?flag=teacherMain");
						return actionForward;
					} else if (teacherGrade == Constants.Teacher_Constants.DEAN) {
						ActionForward actionForward = new ActionForward();
						actionForward.setPath("/deanUrl.do?flag=deanMain");
						return actionForward;
					} else {
						ActionForward actionForward = new ActionForward();
						actionForward.setPath("/adminUrl.do?flag=adminMain");
						return actionForward;
					}
				} else {
					request.getSession().setAttribute("error", 1);
					return mapping.findForward("login");
				}
			}
		}
//		if(username.equals("student")){
//			return mapping.findForward("studentMain");
//		}
//		else if(username.equals("teacher")){
//			return mapping.findForward("teacherMain");
//		}
//		else if(username.equals("dean")){
//			return mapping.findForward("deanMain");
//		}
//		else if(username.equals("admin")){
//			return mapping.findForward("adminMain");
//		}
//		else{
//			return mapping.findForward("adminError");
//		}
	}
}