/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.li.domain.Major;
import com.li.domain.Notice;
import com.li.domain.SubjectType;
import com.li.domain.SystemStatus;
import com.li.domain.Teacher;
import com.li.service.inters.MajorServiceInter;
import com.li.service.inters.NoticeServiceInter;
import com.li.service.inters.SubjectServiceInter;
import com.li.service.inters.SubjectTypeServiceInter;
import com.li.service.inters.SystemStatusServiceInter;
import com.li.service.inters.TeacherServiceInter;
import com.li.util.Constants;

/**
 * MyEclipse Struts Creation date: 05-26-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="flag" scope="request"
 */
public class TeacherUrlAction extends DispatchAction {
	@Resource
	private SubjectTypeServiceInter subjectTypeServiceInter;
	@Resource
	private TeacherServiceInter teacherServiceInter;
	@Resource
	private SystemStatusServiceInter systemStatusServiceInter;
	@Resource
	private NoticeServiceInter noticeServiceInter;
	public void setSubjectTypeServiceInter(
			SubjectTypeServiceInter subjectTypeServiceInter) {
		this.subjectTypeServiceInter = subjectTypeServiceInter;
	}
	public void setNoticeServiceInter(NoticeServiceInter noticeServiceInter) {
		this.noticeServiceInter = noticeServiceInter;
	}
	public void setTeacherServiceInter(
			TeacherServiceInter teacherServiceInter) {
		this.teacherServiceInter = teacherServiceInter;
	}
	public void setSystemStatusServiceInter(
			SystemStatusServiceInter systemStatusServiceInter) {
		this.systemStatusServiceInter = systemStatusServiceInter;
	}
	public ActionForward teacherUploadQuestion(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		SystemStatus systemStatus = systemStatusServiceInter.loadSystemStatusById(1);
		if(systemStatus.getSystemStatus() == 1){

			List<SubjectType> subjectTypes = subjectTypeServiceInter
					.loadSubjectTypes();
			Teacher teacher = (Teacher) request.getSession().getAttribute(
					"teacher");

			int id = teacher.getId();
			List<Major> majors = teacherServiceInter.loadMajors(id);

			request.getSession().setAttribute("subjectTypes", subjectTypes);
			request.getSession().setAttribute("majors", majors);

			return mapping.findForward("teacherUploadQuestion");
		}
		else{
			request.setAttribute("error", "系统暂未开放");
			return mapping.findForward("teacherError");
		}
	}

	public ActionForward teacherChangePwd(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("teacherChangePwd");
	}

	public ActionForward teacherInputFirstAssess(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("teacherInputFirstAssess");
	}

	public ActionForward teacherInputMutualAssess(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("teacherInputMutualAssess");
	}

	public ActionForward teacherInputReplyAssess(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("teacherInputReplyAssess");
	}

	public ActionForward teacherMain(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<Notice> notices = noticeServiceInter.loadNoticesByGrade(Constants.Notice_Constants.NOTICE_GRADE_TEACHER);
		request.setAttribute("notices", notices);
		
		return mapping.findForward("teacherMain");
	}

	public ActionForward teacherOk(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("teacherOk");
	}

	public ActionForward teacherError(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("teacherError");
	}

	public ActionForward teacherDownloadFile(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("teacherDownloadFile");
	}
	public ActionForward teacherCalendar(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("teacherCalendar");
	}
	public ActionForward teacherLogout(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("login");
	}
}