/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.form.student;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-28-2014
 * 
 * XDoclet definition:
 * @struts.form name="chooseSubjectForm"
 */
public class ChooseSubjectForm extends ActionForm {
	private String subjectOne;
	private String subjectTwo;
	private String subjectThree;
	private String subjectTurn;
	public String getSubjectOne() {
		return subjectOne;
	}
	public void setSubjectOne(String subjectOne) {
		this.subjectOne = subjectOne;
	}
	public String getSubjectTwo() {
		return subjectTwo;
	}
	public void setSubjectTwo(String subjectTwo) {
		this.subjectTwo = subjectTwo;
	}
	public String getSubjectThree() {
		return subjectThree;
	}
	public void setSubjectThree(String subjectThree) {
		this.subjectThree = subjectThree;
	}
	public String getSubjectTurn() {
		return subjectTurn;
	}
	public void setSubjectTurn(String subjectTurn) {
		this.subjectTurn = subjectTurn;
	}
}