/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.form.student;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 06-09-2014
 * 
 * XDoclet definition:
 * @struts.form name="uploadFileForm"
 */
public class UploadFileForm extends ActionForm {
	private FormFile myFile;
	private String attachType;
	private String subjectId;
	public FormFile getMyFile() {
		return myFile;
	}
	public void setMyFile(FormFile myFile) {
		this.myFile = myFile;
	}
	public String getAttachType() {
		return attachType;
	}
	public void setAttachType(String attachType) {
		this.attachType = attachType;
	}
	public String getSubjectId() {
		return subjectId;
	}
	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}
}