/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action.admin;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.li.service.inters.SystemStatusServiceInter;
import com.li.struts.form.admin.ChangeStatusForm;

/**
 * MyEclipse Struts Creation date: 06-08-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action
 */
public class ChangeStatusAction extends Action {
	@Resource
	private SystemStatusServiceInter systemStatusServiceInter;
	public void setSystemStatusServiceInter(
			SystemStatusServiceInter systemStatusServiceInter) {
		this.systemStatusServiceInter = systemStatusServiceInter;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ChangeStatusForm changeStatusForm = (ChangeStatusForm) form;
		
		System.out.println("ChangeStatusAction::status1=" + changeStatusForm.getStatus1());
		System.out.println("ChangeStatusAction::status2=" + changeStatusForm.getStatus2());
		System.out.println("ChangeStatusAction::status3=" + changeStatusForm.getStatus3());
		System.out.println("ChangeStatusAction::status4=" + changeStatusForm.getStatus4());

		System.out.println(changeStatusForm.getStatus1());
		
		if(changeStatusForm.getStatus1().equals("1")){
			systemStatusServiceInter.changeSystemStatus(1, 1);
		}
		else{
			systemStatusServiceInter.changeSystemStatus(1, 0);
		}
		
		if(changeStatusForm.getStatus2().equals("1")){
			systemStatusServiceInter.changeSystemStatus(2, 1);
		}
		else{
			systemStatusServiceInter.changeSystemStatus(2, 0);
		}
		
		if(changeStatusForm.getStatus3().equals("1")){
			systemStatusServiceInter.changeSystemStatus(3, 1);
		}
		else{
			systemStatusServiceInter.changeSystemStatus(3, 0);
		}
		
		if(changeStatusForm.getStatus4().equals("1")){
			systemStatusServiceInter.changeSystemStatus(4, 1);
		}
		else{
			systemStatusServiceInter.changeSystemStatus(4, 0);
		}

		return mapping.findForward("adminOk");
	}
}