/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action.admin;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.li.domain.Teacher;
import com.li.service.inters.DeptServiceInter;
import com.li.service.inters.MajorServiceInter;
import com.li.service.inters.TeacherServiceInter;
import com.li.web.domain.TeacherWeb;

/** 
 * MyEclipse Struts
 * Creation date: 06-04-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class UploadTeacherAction extends Action {
	@Resource
	private TeacherServiceInter teacherServiceInter;
	@Resource
	private DeptServiceInter deptServiceInter;
	@Resource
	private MajorServiceInter majorServiceInter;
	public void setTeacherServiceInter(TeacherServiceInter teacherServiceInter) {
		this.teacherServiceInter = teacherServiceInter;
	}
	public void setDeptServiceInter(DeptServiceInter deptServiceInter) {
		this.deptServiceInter = deptServiceInter;
	}
	public void setMajorServiceInter(MajorServiceInter majorServiceInter) {
		this.majorServiceInter = majorServiceInter;
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<TeacherWeb> teacherWebs = (List<TeacherWeb>) request.getSession().getAttribute("teachers");
		for(TeacherWeb teacherWeb : teacherWebs){
			Teacher teacher = new Teacher();
//			Teacher teacher2 = new Teacher(major, dept, teacherId, teacherName, teacherPwd, teacherGrade, teacherTel, teacherEmail);
			
			teacher.setTeacherId(teacherWeb.getTeacherId());
			teacher.setTeacherName(teacherWeb.getTeacherName());
			teacher.setTeacherPwd("123456");
			teacher.setTeacherGrade(Integer.parseInt(teacherWeb.getTeacherGrade()));
			teacher.setTeacherTel(teacherWeb.getTeacherTel());
			teacher.setTeacherEmail(teacherWeb.getTeacherEmail());
			String teacherMajor = teacherWeb.getTeacherMajor();
			teacher.setMajor(majorServiceInter.findMajorByName(teacherMajor));
			teacher.setDept(deptServiceInter.findDeptByName(teacherWeb.getTeacherDept()));
			
			teacherServiceInter.add(teacher);
		}
		request.getSession().removeAttribute("teachers");
		return mapping.findForward("adminMain");
	}
}