/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action.admin;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.li.domain.Clazz;
import com.li.service.inters.ClazzServiceInter;
import com.li.service.inters.MajorServiceInter;
import com.li.web.domain.ClazzWeb;

/** 
 * MyEclipse Struts
 * Creation date: 06-04-2014
 * 
 * XDoclet definition:
 * @struts.action
 */
public class UploadClazzAction extends Action {
	@Resource
	private MajorServiceInter majorServiceInter;
	@Resource
	private ClazzServiceInter clazzServiceInter;
	public void setMajorServiceInter(MajorServiceInter majorServiceInter) {
		this.majorServiceInter = majorServiceInter;
	}
	public void setClazzServiceInter(ClazzServiceInter clazzServiceInter) {
		this.clazzServiceInter = clazzServiceInter;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<ClazzWeb> clazzWebs = (List<ClazzWeb>) request.getSession().getAttribute("clazzs");
		for(ClazzWeb clazzWeb : clazzWebs){
			Clazz clazz = new Clazz();
//			Clazz clazz2 = new Clazz(major, clazzName, clazzGrade)
			
			clazz.setClazzGrade(clazzWeb.getClazzGrade());
			clazz.setClazzName(clazzWeb.getClazzName());
			clazz.setMajor(majorServiceInter.findMajorByName(clazzWeb.getClazzMajor()));
			clazzServiceInter.add(clazz);
		}
		request.getSession().removeAttribute("clazzs");
		return mapping.findForward("adminMain");
	}
}