/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action.admin;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.li.domain.Major;
import com.li.service.inters.DeptServiceInter;
import com.li.service.inters.MajorServiceInter;
import com.li.web.domain.MajorWeb;

/** 
 * MyEclipse Struts
 * Creation date: 06-04-2014
 * 
 * XDoclet definition:
 * @struts.action
 */
public class UploadMajorAction extends Action {
	@Resource
	private DeptServiceInter deptServiceInter;
	@Resource
	private MajorServiceInter majorServiceInter;
	public void setDeptServiceInter(DeptServiceInter deptServiceInter) {
		this.deptServiceInter = deptServiceInter;
	}
	public void setMajorServiceInter(MajorServiceInter majorServiceInter) {
		this.majorServiceInter = majorServiceInter;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<MajorWeb> majorWebs = (List<MajorWeb>) request.getSession().getAttribute("majors");
		for(MajorWeb majorWeb : majorWebs){
			Major major = new Major();
			major.setDept(deptServiceInter.findDeptByName(majorWeb.getMajorDept()));
			major.setMajorName(majorWeb.getMajorName());
			majorServiceInter.add(major);
		}
		
		request.getSession().removeAttribute("majors");
		return mapping.findForward("adminMain");
	}
}