/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action.admin;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.li.domain.Dept;
import com.li.service.inters.DeptServiceInter;
import com.li.web.domain.DeptWeb;

/** 
 * MyEclipse Struts
 * Creation date: 06-04-2014
 * 
 * XDoclet definition:
 * @struts.action
 */
public class UploadDeptAction extends Action {
	@Resource
	private DeptServiceInter deptServiceInter;
	public void setDeptServiceInter(DeptServiceInter deptServiceInter) {
		this.deptServiceInter = deptServiceInter;
	}
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<DeptWeb> deptWebs = (List<DeptWeb>) request.getSession().getAttribute("depts");
		for(DeptWeb deptWeb : deptWebs){
			Dept dept = new Dept();
			dept.setDeptName(deptWeb.getDeptName());
			dept.setDeptTel(deptWeb.getDeptTel());
			deptServiceInter.add(dept);
		}
		request.getSession().removeAttribute("depts");
		return mapping.findForward("adminMain");
	}
}