/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.form.admin;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-05-2014
 * 
 * XDoclet definition:
 * @struts.form name="queryStudentForm"
 */
public class QueryStudentForm extends ActionForm {
	private String studentName;
	private String studentId;
	private String studentClazzName;
	private String studentMajorId;
	public String getStudentName() {
		return studentName;
	}
	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}
	public String getStudentId() {
		return studentId;
	}
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}
	public String getStudentClazzName() {
		return studentClazzName;
	}
	public void setStudentClazzName(String studentClazzName) {
		this.studentClazzName = studentClazzName;
	}
	public String getStudentMajorId() {
		return studentMajorId;
	}
	public void setStudentMajorId(String studentMajorId) {
		this.studentMajorId = studentMajorId;
	}
}