/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action.student;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.li.domain.Student;
import com.li.service.inters.StudentServiceInter;
import com.li.struts.form.student.ChangePwdForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-02-2014
 * 
 * XDoclet definition:
 * @struts.action
 */
public class ChangePwdAction extends Action {
	@Resource
	private StudentServiceInter studentServiceInter;
	public void setStudentServiceInter(StudentServiceInter studentServiceInter) {
		this.studentServiceInter = studentServiceInter;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ChangePwdForm changePwdForm = (ChangePwdForm)form;
		
		String newPwd = changePwdForm.getNewPwd();
		String oldPwd = changePwdForm.getOldPwd();
		Student student = (Student) request.getSession().getAttribute("student");
		
		boolean success = studentServiceInter.changePwd(student, oldPwd, newPwd);
		if(success){
			return mapping.findForward("studentOk");
		}
		else{
			return mapping.findForward("studentError");
		}
	}
}