/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.action.student;

import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.li.domain.Student;
import com.li.domain.Subject;
import com.li.domain.Volunteer;
import com.li.service.inters.VolunteerServiceInter;
import com.li.struts.form.student.ChooseSubjectForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-28-2014
 * 
 * XDoclet definition:
 * @struts.action
 */
public class ChooseSubjectAction extends Action {
	@Resource
	private VolunteerServiceInter volunteerServiceInter;
	public void setVolunteerServiceInter(VolunteerServiceInter volunteerServiceInter) {
		this.volunteerServiceInter = volunteerServiceInter;
	}
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		//添加学生
		ChooseSubjectForm chooseSubjectForm = (ChooseSubjectForm)form;
		int subjectOne = Integer.parseInt(chooseSubjectForm.getSubjectOne());
		int subjectTwo = Integer.parseInt(chooseSubjectForm.getSubjectTwo());
		int subjectThree = Integer.parseInt(chooseSubjectForm.getSubjectThree());
		int subjectTurn = Integer.parseInt(chooseSubjectForm.getSubjectTurn());
		
		Subject subject_1 = (Subject) volunteerServiceInter.findById(Subject.class, subjectOne);
		Subject subject_2 = (Subject) volunteerServiceInter.findById(Subject.class, subjectTwo);
		Subject subject_3 = (Subject) volunteerServiceInter.findById(Subject.class, subjectThree);
		Student student = (Student) request.getSession().getAttribute("student");
		Date date = new Date();
		Volunteer volunteer1 = new Volunteer(student, subject_1, 1, date.getTime(), subjectTurn);
		volunteerServiceInter.add(volunteer1);
		Volunteer volunteer2 = new Volunteer(student, subject_2, 2, date.getTime(), subjectTurn);
		volunteerServiceInter.add(volunteer2);
		Volunteer volunteer3 = new Volunteer(student, subject_3, 3, date.getTime(), subjectTurn);
		volunteerServiceInter.add(volunteer3);
		
		return mapping.findForward("studentOk");
	}
}