/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.li.struts.form.teacher;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-19-2014
 * 
 * XDoclet definition:
 * @struts.form name="uploadQuestionForm"
 */
public class UploadQuestionForm extends ActionForm {

	private String questionType;
	private String questionName;
	private String questionMajor;
	private String questionInfo;
	public String getQuestionType() {
		return questionType;
	}
	public void setQuestionType(String questionType) {
		this.questionType = questionType;
	}
	public String getQuestionName() {
		return questionName;
	}
	public void setQuestionName(String questionName) {
		this.questionName = questionName;
	}
	public String getQuestionMajor() {
		return questionMajor;
	}
	public void setQuestionMajor(String questionMajor) {
		this.questionMajor = questionMajor;
	}
	public String getQuestionInfo() {
		return questionInfo;
	}
	public void setQuestionInfo(String questionInfo) {
		this.questionInfo = questionInfo;
	}
}